- name: Import APT GPG Key
  ansible.builtin.apt_key:
    state: present
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Microsoft AZ CLI Repository
  ansible.builtin.apt_repository:
    state: present
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_facts['distribution_release'] }} main"
    update_cache: true

# - name: Add Microsoft Package Repository
#   ansible.builtin.apt:
#     deb: |
#       "https://packages.microsoft.com/config/{{ ansible_facts['distribution']|lower }}/{{ ansible_facts['distribution_version'] }}/packages-microsoft-prod.deb"

- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: yes
