---
- name: Verify
  hosts: all
  tasks:
  - name: Get list of installed packages
    ansible.builtin.package_facts:
      manager: auto

  - name: Verify PowerShell is installed
    ansible.builtin.assert:
      that: ansible_facts['packages']['powershell'] is defined
