---
# tasks file for powershell
- name: Import OS Tasks for Repository Configuration
  ansible.builtin.include_tasks: "repository-{{ ansible_os_family }}.yml"

- name: Install the PowerShell Package
  ansible.builtin.package:
    state: present
    name: powershell
