- name: Import RPM Key
  ansible.builtin.rpm_key:
    state: present
    key: "https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }}/gpg"

- name: Configure Doker CE Package Repository
  ansible.builtin.yum_repository:
    state: present
    name: docker-ce-stable
    baseurl: "https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }}/{{ ansible_facts['distribution_major_version'] }}/{{ ansible_facts['architecture'] }}/stable" # noqa 204
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }}/gpg"
    description: "Docker CE Stable - {{ ansible_facts['architecture'] }}"
