- name: Import Docker GPG Key
  ansible.builtin.apt_key:
    state: present
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }}/gpg"

- name: Add Docker CE Repository
  ansible.builtin.apt_repository:
    state: present
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }} {{ ansible_facts['distribution_release'] }} stable" # noqa 204
    update_cache: true
