---
- name: Verify
  hosts: all
  tasks:
  - name: Get list of installed packages
    ansible.builtin.package_facts:
      manager: auto

  - name: Verify Docker packages are installed
    ansible.builtin.assert:
      that:
        - ansible_facts['packages']['docker-ce'] is defined
        - ansible_facts['packages']['docker-ce-cli'] is defined
        - ansible_facts['packages']['containerd.io'] is defined
