name: YAML Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  yamllint:
    name: Verify yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v1
